language: php
php:
  - 5.4
env:
  - DB=mysql
before_script:
  # everything after this point is needed to just use phpunit
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/PHP_Invoker
  - pear install phpunit/DbUnit
  - pear install phpunit/PHPUnit_Selenium
  - pear install phpunit/PHPUnit_Story
   - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi
script: 
  - phpunit -c protected/tests/ protected/tests/unit/PostTest.php
  - phpunit -c protected/tests/ protected/tests/functional/commentTest.php
